from pathlib import Path


APP_NAME = "Enigma Machine Raspberry"
HOST = "0.0.0.0"
PORT = 8000
STATE_FILE = Path("state/enigma_state.json")

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
ROTOR_WIRINGS = {
    "I": "EKMFLGDQVZNTOWYHXUSPAIBRCJ",
    "II": "AJDKSIRUXBLHWTMCQGZNPYFVOE",
    "III": "BDFHJLCPRTXVZNYEIWGAKMUSQO",
}
REFLECTOR_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
